FROM python:3.9-slim-buster

ENV DEBIAN_FRONTEND=noninteractive \
    PATH="/root/.local/bin:$PATH"

# Set the working directory in the container
WORKDIR /backend

# Install required system packages
RUN apt-get update && apt-get install -y --no-install-recommends \
    git \
    curl \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# Upgrade pip and install poetry
RUN pip3 install --upgrade pip \
    && pip3 install poetry

# Install the project requirements
COPY pyproject.toml poetry.lock ./
RUN poetry env use python \
    && poetry config virtualenvs.create false \
    && poetry install --no-interaction --no-ansi

# Copy the rest of the application code
COPY app.py /backend/
COPY routes.py /backend/
COPY services /backend/services

ENTRYPOINT ["python", "app.py"]

# Expose the default port for Flask
EXPOSE 5000

# Cleanup
RUN poetry cache clear --all pypi
